In [6]:
import numpy as np


In [12]:
sales = np.array([150, 320, 89, 410, 275, 95, 380, 220])

sales_above_200 = sales[sales > 200]
print(sales_above_200)

sales_between_100_300 = sales[(sales>=100) & (sales<=300)]
print(sales_between_100_300)

lowest_index = np.argmin(sales)
print("Index of lowest sales:", lowest_index)

replaced_sales = np.where(sales < 100, 100, sales)
print(replaced_sales)
print(40 * '-')

result = replaced_sales
 
print("Original:", sales)
print("Replaced:", result)

[320 410 275 380 220]
[150 275 220]
Index of lowest sales: 2
[150 320 100 410 275 100 380 220]
----------------------------------------
Original: [150 320  89 410 275  95 380 220]
Replaced: [150 320 100 410 275 100 380 220]
