In [1]:
import numpy as np

In [2]:
sales_matrix = np.array([
    [100, 150, 200, 175],
    [120, 180, 160, 190],
    [90, 210, 185, 165]
])

print("Sales Matrix:")
print(sales_matrix)
print(f"\nShape of the sales matrix: {sales_matrix.shape}")
print(f"Data type of the sales matrix: {sales_matrix.ndim}")
print(f"Total number of elements in the sales matrix: {sales_matrix.size}")


Sales Matrix:
[[100 150 200 175]
 [120 180 160 190]
 [ 90 210 185 165]]

Shape of the sales matrix: (3, 4)
Data type of the sales matrix: 2
Total number of elements in the sales matrix: 12
